src/objects/Alumno__c.object
<CustomObject>
    <label>Alumno</label>
    <nameField>
        <label>Alumno Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alumnos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asistencia__c.object
<CustomObject>
    <fields>
        <fullName>Alumno__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Alumno</label>
        <referenceTo>Alumno__c</referenceTo>
        <relationshipLabel>Asistencias</relationshipLabel>
        <relationshipName>Asistencias</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clase__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Clase</label>
        <referenceTo>Clase__c</referenceTo>
        <relationshipLabel>Asistencias</relationshipLabel>
        <relationshipName>Asistencias</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hora__c</fullName>
        <label>Hora</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Asistencia</label>
    <nameField>
        <label>Asistencia Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asistencias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clase__c.object
<CustomObject>
    <fields>
        <fullName>Materia__c</fullName>
        <label>Materia</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Español</fullName>
                </value>
                <value>
                    <fullName>Matematicas</fullName>
                </value>
                <value>
                    <fullName>Quimica</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Clase</label>
    <nameField>
        <label>Clase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgendaController.cls
public with sharing class AgendaController {
    public static Alumno__c searchAlumno(String nombreAlumno){
        return [SELECT Id FROM Alumno__c WHERE Name=:nombreAlumno];

    }

    public static Clase__c searchClase(String nombreClase){
        return[SELECT Id FROM Clase__c WHERE Name=:nombreClase];
    }
    @AuraEnabled
    public static List<Asistencia__c> getAllAsistencia(){
        return[SELECT Id, Name, Alumno__r.Name, Clase__r.Materia__c, Hora__c FROM Asistencia__c];
    }

    @AuraEnabled
    public static Asistencia__c deleteAsistencia(Asistencia__c asiss){
        delete asiss;
        return asiss;
    }

    
    @AuraEnabled
    public static String agendar(Id name, Id materia, Datetime hora){
    try{
        
        Asistencia__c newas = new Asistencia__c(Clase__c=materia, Alumno__c=name, Hora__c = hora);
        insert newas;

    }catch(Exception e){
        return e.getMessage();
    }
    return 'Saved';
    }

    

}